//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erwine.Leonard.T.SsmlNotePad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Markup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Markup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Erwine.Leonard.T.SsmlNotePad.Markup", typeof(Markup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak version=&quot;1.0&quot; xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xml:lang=&quot;en-US&quot;&gt;
        ///
        ///&lt;/speak&gt;.
        /// </summary>
        internal static string BlankSsmlDocument {
            get {
                return ResourceManager.GetString("BlankSsmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;speak version=&quot;1.0&quot; xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xml:lang=&quot;en-US&quot;&gt;
        ///  Simple text
        ///  With newline.
        ///  &lt;emphasis&gt;Test PromptEmphasis.NotSet&lt;/emphasis&gt;
        ///  &lt;emphasis level=&quot;strong&quot;&gt;Test PromptEmphasis.Strong&lt;/emphasis&gt;
        ///  &lt;emphasis level=&quot;moderate&quot;&gt;Test PromptEmphasis.Moderate&lt;/emphasis&gt;
        ///  &lt;emphasis level=&quot;none&quot;&gt;Test PromptEmphasis.None&lt;/emphasis&gt;
        ///  &lt;emphasis level=&quot;reduced&quot;&gt;Test PromptEmphasis.Reduced&lt;/emphasis&gt;
        ///    &lt;prosody&gt;Test PromptVolume.NotSet&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleSsmlDocument {
            get {
                return ResourceManager.GetString("SampleSsmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	    elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xsd:annotation&gt;
        ///    &lt;xsd:documentation&gt;SSML 1.0 Core Schema (20040615)&lt;/xsd:documentation&gt;
        ///  &lt;/xsd:annotation&gt;
        ///  &lt;xsd:annotation&gt;
        ///    &lt;xsd:documentation&gt;
        ///      Copyright 1998-2004 W3C (MIT, ERCIM, Keio),
        ///      All Rights Reserved. Permission to use, copy, modify and
        ///      distribute the SSML core schema and its accompanying documentation
        ///      for any purpose and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SsmlCore {
            get {
                return ResourceManager.GetString("SsmlCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema targetNamespace=&quot;http://www.w3.org/2001/10/synthesis&quot;
        ///xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xsd:annotation&gt;
        ///    &lt;xsd:documentation&gt;SSML 1.0 Schema (20040615)&lt;/xsd:documentation&gt;
        ///  &lt;/xsd:annotation&gt;
        ///  &lt;xsd:annotation&gt;
        ///    &lt;xsd:documentation&gt;
        ///      Copyright 1998-2004 W3C (MIT, ERCIM, Keio),
        ///      All Rights Reserved. Permission to use, copy, modify and
        ///      dist [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SsmlSchema {
            get {
                return ResourceManager.GetString("SsmlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- This file was generated using the dtd2xsd tool --&gt;
        ///&lt;xs:schema xmlns=&quot;http://schemas.microsoft.com/Visual-Studio-Intellisense&quot; elementFormDefault=&quot;qualified&quot;  attributeFormDefault=&quot;qualified&quot;
        ///  targetNamespace=&quot;http://schemas.microsoft.com/Visual-Studio-Intellisense&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;!-- global attributes for annotating schemas with information for intellisense --&gt;
        ///  &lt;xs:attribute name=&quot;builder&quot; type=&quot;xs:string&quot;  /&gt;
        ///
        ///  &lt;!-- g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VsiSchema {
            get {
                return ResourceManager.GetString("VsiSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- 
        ///    Copyright © 2001 World Wide Web Consortium, (Massachusetts Institute of 
        ///    Technology, European Research Consortium for Informatics and Mathematics,
        ///    Keio University). All Rights Reserved. This work is distributed under
        ///    the W3C® Software License [1] .  
        ///    
        ///    [1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
        ///        
        ///    Portions © 2004-2005 Microsoft Corporation.  All rights reserved.  
        ///    This file was derived fr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XhtmlSchema {
            get {
                return ResourceManager.GetString("XhtmlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- 
        ///  Copyright 2001 World Wide Web Consortium, (Massachusetts Institute of Technology, European Research 
        ///  Consortium for Informatics and Mathematics, Keio University). All Rights Reserved. 
        ///  http://www.w3.org/Consortium/Legal/2002/copyright-documents-20021231&quot; 
        ///  
        ///  This schema is copied from http://www.w3.org/2001/xml.xsd.
        ///--&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSchema {
            get {
                return ResourceManager.GetString("XmlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;!DOCTYPE xs:schema SYSTEM &quot;XMLSchema.dtd&quot; [
        ///&lt;!ELEMENT p ANY&gt;
        ///&lt;!ELEMENT a ANY&gt;
        ///&lt;!ATTLIST a href CDATA #IMPLIED&gt;
        ///&lt;!ELEMENT hr ANY&gt;
        ///&lt;!ELEMENT h1 ANY&gt;
        ///&lt;!ELEMENT br ANY&gt;
        ///]&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///   &lt;xs:documentation&gt;
        ///    &lt;h1&gt;XML Schema instance namespace&lt;/h1&gt;
        ///    &lt;p&gt;See &lt;a href=&quot;http://www.w3.org/TR/xmlsche [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSchemaInstance {
            get {
                return ResourceManager.GetString("XmlSchemaInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- 
        ///Copyright © 2001 World Wide Web Consortium, (Massachusetts Institute of 
        ///Technology, European Research Consortium for Informatics and Mathematics,
        ///Keio University). All Rights Reserved. This work is distributed under
        ///the W3C® Software License [1] .  
        /// 
        ///[1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
        /// 
        ///Portions © 2004-2007 Microsoft Corporation.  All rights reserved.  
        ///  This file was derived from http://www.w3.org/2001/XMLSchema. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XsdSchema {
            get {
                return ResourceManager.GetString("XsdSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///    Copyright © 2001 World Wide Web Consortium, (Massachusetts Institute of
        ///    Technology, European Research Consortium for Informatics and Mathematics,
        ///    Keio University). All Rights Reserved. This work is distributed under
        ///    the W3C® Software License [1].
        ///
        ///    [1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
        ///
        ///    Portions © 2004-2009 Microsoft Corporation.  All rights reserved.
        ///    This file was derived from http://www.w3.or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XsltSchema {
            get {
                return ResourceManager.GetString("XsltSchema", resourceCulture);
            }
        }
    }
}
