//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Markup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Markup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestProject1.Markup", typeof(Markup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;speak version=&quot;1.0&quot; xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xml:lang=&quot;en-US&quot;&gt;
        ///  &lt;meta name=&quot;EncodingApplication&quot; content=&quot;SsmlNotePad, Version=1.0.0.1, Culture=neutral, PublicKeyToken=83f27502d5818d53&quot; /&gt;
        ///  &lt;emphasis&gt;Test PromptEmphasis.NotSet&lt;/emphasis&gt;
        ///  &lt;emphasis level=&quot;strong&quot;&gt;Test PromptEmphasis.Strong&lt;/emphasis&gt;
        ///  &lt;emphasis level=&quot;moderate&quot;&gt;Test PromptEmphasis.Moderate&lt;/emphasis&gt;
        ///  &lt;emphasis level=&quot;none&quot;&gt;Test PromptEmphasis.None&lt;/emphasis&gt;
        ///  &lt;emphasi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleSsml1 {
            get {
                return ResourceManager.GetString("ExampleSsml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvalidSsml {
            get {
                return ResourceManager.GetString("InvalidSsml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!DOCTYPE sgml [
        ///  &lt;!ELEMENT sgml (img)*&gt;
        ///   &lt;!--
        ///     the optional &quot;type&quot; attribute value can only be set to this notation.
        ///   --&gt;
        ///  &lt;!ATTLIST sgml type  NOTATION (type-vendor-specific ) #IMPLIED&gt;
        ///
        ///  &lt;!ELEMENT img ANY&gt; &lt;!-- optional content can be only parsable SGML or XML data --&gt;
        ///   &lt;!--
        ///     The optional &quot;title&quot; attribute value must be parsable as text.
        ///     The optional &quot;data&quot; attribute value is set to an unparsed external entity.
        ///     The optional &quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlDocTypeTest {
            get {
                return ResourceManager.GetString("XmlDocTypeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;sgml type=&quot;type-vendor-specific&quot;&gt;
        ///  &lt;!-- an SVG image is parsable as valid SGML or XML text --&gt;
        ///  &lt;img title=&quot;&amp;lt;&quot; type=&quot;type-image-svg&quot;&gt;&amp;amp;&lt;/img&gt;
        ///
        ///  &lt;!--  a GIF image is not parsable and can only be referenced as an external entity --&gt;
        ///  &lt;img title=&quot;&amp;gt;&quot; data=&quot;example1GIF&quot; /&gt;
        ///  &lt;!--No more --&gt;
        ///&lt;/sgml&gt;.
        /// </summary>
        internal static string XmlText {
            get {
                return ResourceManager.GetString("XmlText", resourceCulture);
            }
        }
    }
}
