//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erwine.Leonard.T.SsmlNotePad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources")]
        public string RelativeXmlBaseURI {
            get {
                return ((string)(this["RelativeXmlBaseURI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BlankSsmlDocument.xml")]
        public string BlankSsmlFileName {
            get {
                return ((string)(this["BlankSsmlFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SampleSsmlDocument.xml")]
        public string SampleSsmlFileName {
            get {
                return ((string)(this["SampleSsmlFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visual-Studio-Intellisense.xsd")]
        public string VsiFileName {
            get {
                return ((string)(this["VsiFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WindowsPhoneSynthesis.xsd")]
        public string SsmlSchemaFileName {
            get {
                return ((string)(this["SsmlSchemaFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WindowsPhoneSynthesis-core.xsd")]
        public string SsmlSchemaCoreFileName {
            get {
                return ((string)(this["SsmlSchemaCoreFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xhtml.xsd")]
        public string XhtmlSchemaFileName {
            get {
                return ((string)(this["XhtmlSchemaFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xml.xsd")]
        public string XmlSchemaFileName {
            get {
                return ((string)(this["XmlSchemaFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XMLSchema-instance.xsd")]
        public string SchemaInstanceFileName {
            get {
                return ((string)(this["SchemaInstanceFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xsdschema.xsd")]
        public string XsdSchemaFileName {
            get {
                return ((string)(this["XsdSchemaFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xslt.xsd")]
        public string XsltSchemaFileName {
            get {
                return ((string)(this["XsltSchemaFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".ssml")]
        public string SsmlFileExtension {
            get {
                return ((string)(this["SsmlFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.w3.org/TR/speech-synthesis/")]
        public string SsmlSchemaDocumentationUrl {
            get {
                return ((string)(this["SsmlSchemaDocumentationUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.w3.org/TR/speech-synthesis/synthesis.dtd")]
        public string SsmlDocTypeURI {
            get {
                return ((string)(this["SsmlDocTypeURI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Speech Synthesis Markup Language Source")]
        public string SsmlFileTypeDescriptionLong {
            get {
                return ((string)(this["SsmlFileTypeDescriptionLong"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Speech Synthesis Markup")]
        public string SsmlFileTypeDescriptionShort {
            get {
                return ((string)(this["SsmlFileTypeDescriptionShort"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSsmlFilePath {
            get {
                return ((string)(this["LastSsmlFilePath"]));
            }
            set {
                this["LastSsmlFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSavedWavPath {
            get {
                return ((string)(this["LastSavedWavPath"]));
            }
            set {
                this["LastSavedWavPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAudioPath {
            get {
                return ((string)(this["LastAudioPath"]));
            }
            set {
                this["LastAudioPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastBrowsedSubdirectory {
            get {
                return ((string)(this["LastBrowsedSubdirectory"]));
            }
            set {
                this["LastBrowsedSubdirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-11")]
        public int DefaultSpeechRate {
            get {
                return ((int)(this["DefaultSpeechRate"]));
            }
            set {
                this["DefaultSpeechRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DefaultSpeechVolume {
            get {
                return ((int)(this["DefaultSpeechVolume"]));
            }
            set {
                this["DefaultSpeechVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultVoiceName {
            get {
                return ((string)(this["DefaultVoiceName"]));
            }
            set {
                this["DefaultVoiceName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.w3.org/TR/pronunciation-lexicon/")]
        public string PlsSchemaDocumentationUrl {
            get {
                return ((string)(this["PlsSchemaDocumentationUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".pls")]
        public string PlsFileExtension {
            get {
                return ((string)(this["PlsFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://msdn.microsoft.com/en-us/library/hh361605(v=office.14).aspx")]
        public string AltPlsSchemaDocumentationUrl {
            get {
                return ((string)(this["AltPlsSchemaDocumentationUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://msdn.microsoft.com/en-us/library/office/hh361578(v=office.14).aspx")]
        public string AltSsmlSchemaDocumentationUrl {
            get {
                return ((string)(this["AltSsmlSchemaDocumentationUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pronunciation Lexicon")]
        public string PlsFileTypeDescriptionShort {
            get {
                return ((string)(this["PlsFileTypeDescriptionShort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pronunciation Lexicon Source")]
        public string PlsFileTypeDescriptionLong {
            get {
                return ((string)(this["PlsFileTypeDescriptionLong"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pls.xsd")]
        public string PlsSchemaFileName {
            get {
                return ((string)(this["PlsSchemaFileName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPlsFilePath {
            get {
                return ((string)(this["LastPlsFilePath"]));
            }
            set {
                this["LastPlsFilePath"] = value;
            }
        }
    }
}
